"""Populate ``paper/include/experiment`` with benchmark-backed LaTeX snippets.

Run via ``python -m research_lab.paper`` or ``make paper-bench``. This module is
optional at runtime: failures are logged and stub TeX is written so
``main.tex`` still encodes the intended structure.

The harness now generates three experiment subsections:

1.  Standard HF leaderboard benchmarks (multiple-choice + generation).
2.  Broca architecture probes (bare LM vs full stack).
3.  **Substrate-specific benchmarks** — rule-shift, adversarial resistance,
    causal reasoning, memory fidelity, conformal coverage, VSA algebra,
    Hopfield retrieval, and active-inference decision quality.

Each subsection produces both tables and dynamically generated prose that
accurately describes the experiment results. The prose is templatized with
conditional logic so the narrative adjusts to the actual numbers.
"""

from __future__ import annotations

import json
import logging
import math
import os
import shutil
import subprocess
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Mapping

logger = logging.getLogger(__name__)


def repo_root() -> Path:
    """Repository root (parent of ``paper/``)."""
    return Path(__file__).resolve().parents[2]


def paper_dirs(root: Path | None = None) -> tuple[Path, Path]:
    r = repo_root() if root is None else Path(root)
    paper = r / "paper"
    exp = paper / "include" / "experiment"
    return paper, exp


def _git_head(cwd: Path) -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            cwd=cwd,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


def write_bench_run_provenance_tex(
    exp_dir: Path,
    *,
    iso_timestamp: str,
    commit_hash: str,
    run_id: str,
    native_artifact: str,
    substrate_seed: int,
) -> None:
    """Emit LaTeX macros consumed by ``experiments.tex`` for benchmark provenance."""
    path = exp_dir / "_bench_run_provenance.tex"
    lines = [
        "% Auto-generated by research_lab.paper.harness.refresh_paper_experiments",
        rf"\newcommand{{\BenchRunTimestamp}}{{{iso_timestamp}}}",
        rf"\newcommand{{\BenchRunCommit}}{{\texttt{{{commit_hash}}}}}",
        rf"\newcommand{{\BenchRunId}}{{\texttt{{\detokenize{{{run_id}}}}}}}",
        rf"\newcommand{{\BenchRunNativeArtifact}}{{\texttt{{\detokenize{{{native_artifact}}}}}}}",
        rf"\newcommand{{\BenchRunSeed}}{{{substrate_seed}}}",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _latex_escape(s: str) -> str:
    return (
        str(s)
        .replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("$", r"\$")
        .replace("#", r"\#")
        .replace("_", r"\_")
        .replace("{", r"\{")
        .replace("}", r"\}")
        .replace("~", r"\textasciitilde{}")
        .replace("^", r"\textasciicircum{}")
    )


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name)
    if raw is None or not str(raw).strip():
        return int(default)
    try:
        return int(str(raw).strip())
    except ValueError:
        return int(default)


def _pct(v: float) -> str:
    """Format a fraction as a percentage string for prose."""
    return f"{v * 100:.1f}\\%"


def _qual(acc: float) -> str:
    """Return a qualitative descriptor for an accuracy value."""
    if acc >= 0.95:
        return "near-perfect"
    if acc >= 0.85:
        return "strong"
    if acc >= 0.70:
        return "moderate"
    if acc >= 0.50:
        return "modest"
    return "weak"


def _direction(delta: float, threshold: float = 0.005) -> str:
    """Return a prose direction word for a delta."""
    if abs(delta) < threshold:
        return "negligible"
    return "positive" if delta > 0 else "negative"


def _delta_tex(delta: float, *, prec: int = 3) -> str:
    """Format a delta for LaTeX text (omit misleading ``+`` on zeros)."""
    if delta == 0.0:
        return f"{0:.{prec}f}"
    return f"{delta:+.{prec}f}"


# ---------------------------------------------------------------------------
# HF native benchmark tables and prose
# ---------------------------------------------------------------------------

def write_vanilla_table_tex(summary: Mapping[str, Any], dest: Path) -> None:
    per_task = summary.get("per_task") or {}
    lines = [
        r"\begin{tabular}{lrr}",
        r"\toprule",
        r"Task & $n$ & Accuracy \\",
        r"\midrule",
    ]
    for task in sorted(per_task.keys()):
        m = per_task[task]
        if not isinstance(m, Mapping):
            continue
        safe_task = _latex_escape(str(task))
        lines.append(
            f"{safe_task} & {m.get('n', '')} & {float(m.get('accuracy', 0.0)):.4f} \\\\",
        )
    agg = summary.get("aggregate") or {}
    macro = float(agg.get("macro_accuracy", 0.0))
    micro = float(agg.get("micro_accuracy", 0.0))
    lines.extend([
        r"\midrule",
        f"\\textit{{Macro avg}} & & {macro:.4f} \\\\",
        f"\\textit{{Micro avg}} & {agg.get('micro_n', '')} & {micro:.4f} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ])
    dest.write_text("\n".join(lines), encoding="utf-8")


def write_comparison_table_tex(summary: Mapping[str, Any], dest: Path) -> None:
    per_v = summary.get("per_task") or {}
    comp = summary.get("comparison") or {}
    shell = (comp.get("llama_broca_shell") or {}).get("per_task") or {}
    mind = (comp.get("broca_mind") or {}).get("per_task") or {}
    tasks = sorted(set(per_v.keys()) & set(shell.keys()))
    if mind:
        tasks = sorted(set(tasks) & set(mind.keys()))
    if not tasks:
        dest.write_text("% (no paired comparison in summary)\n", encoding="utf-8")
        return
    if mind:
        lines = [
            r"\begin{tabular}{lrrrrrr}",
            r"\toprule",
            r"Task & $n$ & Vanilla & Broca shell & Broca mind & $\Delta$(sh$-$va) & $\Delta$(mi$-$va) \\",
            r"\midrule",
        ]
        for task in tasks:
            pv = per_v[task]
            ps = shell[task]
            pm = mind[task]
            if not isinstance(pv, Mapping) or not isinstance(ps, Mapping) or not isinstance(pm, Mapping):
                continue
            acc_v = float(pv.get("accuracy", 0.0))
            acc_s = float(ps.get("accuracy", 0.0))
            acc_m = float(pm.get("accuracy", 0.0))
            n = int(pv.get("n", 0))
            safe_task = _latex_escape(str(task))
            lines.append(
                f"{safe_task} & {n} & {acc_v:.4f} & {acc_s:.4f} & {acc_m:.4f} & "
                f"{_delta_tex(acc_s - acc_v, prec=4)} & {_delta_tex(acc_m - acc_v, prec=4)} \\\\",
            )
        v_agg = summary.get("aggregate") or {}
        shell_agg = (comp.get("llama_broca_shell") or {}).get("aggregate") or {}
        mind_agg = (comp.get("broca_mind") or {}).get("aggregate") or {}
        v_macro = float(v_agg.get("macro_accuracy", 0.0))
        s_macro = float(shell_agg.get("macro_accuracy", 0.0))
        m_macro = float(mind_agg.get("macro_accuracy", 0.0))
        micro_n = int(v_agg.get("micro_n", 0))
        v_micro = float(v_agg.get("micro_accuracy", 0.0))
        s_micro = float(shell_agg.get("micro_accuracy", 0.0))
        m_micro = float(mind_agg.get("micro_accuracy", 0.0))
        lines.extend([
            r"\midrule",
            f"\\textit{{Macro avg}} & & {v_macro:.4f} & {s_macro:.4f} & {m_macro:.4f} & "
            f"{_delta_tex(s_macro - v_macro, prec=4)} & {_delta_tex(m_macro - v_macro, prec=4)} \\\\",
            f"\\textit{{Micro avg}} & {micro_n} & {v_micro:.4f} & {s_micro:.4f} & {m_micro:.4f} & "
            f"{_delta_tex(s_micro - v_micro, prec=4)} & {_delta_tex(m_micro - v_micro, prec=4)} \\\\",
            r"\bottomrule",
            r"\end{tabular}",
            "",
        ])
        dest.write_text("\n".join(lines), encoding="utf-8")
        return
    lines = [
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Task & $n$ & Vanilla & Broca shell & $\Delta$ \\",
        r"\midrule",
    ]
    for task in tasks:
        pv = per_v[task]
        ps = shell[task]
        if not isinstance(pv, Mapping) or not isinstance(ps, Mapping):
            continue
        acc_v = float(pv.get("accuracy", 0.0))
        acc_s = float(ps.get("accuracy", 0.0))
        n = int(pv.get("n", 0))
        safe_task = _latex_escape(str(task))
        lines.append(
            f"{safe_task} & {n} & {acc_v:.4f} & {acc_s:.4f} & {_delta_tex(acc_s - acc_v, prec=4)} \\\\",
        )
    shell_agg = (comp.get("llama_broca_shell") or {}).get("aggregate") or {}
    v_agg = summary.get("aggregate") or {}
    v_macro = float(v_agg.get("macro_accuracy", 0.0))
    s_macro = float(shell_agg.get("macro_accuracy", 0.0))
    lines.extend([
        r"\midrule",
        f"\\textit{{Macro avg}} & & {v_macro:.4f} & {s_macro:.4f} & {_delta_tex(s_macro - v_macro, prec=4)} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ])
    dest.write_text("\n".join(lines), encoding="utf-8")


def _has_paired_shell_comparison(summary: Mapping[str, Any]) -> bool:
    comp = summary.get("comparison")
    if not isinstance(comp, Mapping) or not comp:
        return False
    shell = (comp.get("llama_broca_shell") or {}).get("per_task") or {}
    per_v = summary.get("per_task") or {}
    return bool(set(per_v.keys()) & set(shell.keys()))


def _has_broca_mind_in_comparison(summary: Mapping[str, Any]) -> bool:
    comp = summary.get("comparison") or {}
    mind = (comp.get("broca_mind") or {}).get("per_task") or {}
    return bool(mind)


def _generate_hf_native_prose(summary: Mapping[str, Any]) -> str:
    """Generate dynamic prose describing the HF benchmark results."""
    per_task = summary.get("per_task") or {}
    agg = summary.get("aggregate") or {}
    macro = float(agg.get("macro_accuracy", 0.0))
    micro = float(agg.get("micro_accuracy", 0.0))
    micro_n = int(agg.get("micro_n", 0))
    model_id = str(summary.get("model_id", "the evaluated model"))
    tasks = list(per_task.keys())
    n_tasks = len(tasks)

    # Find best and worst tasks (summary may omit ``per_task``, e.g. partial fixtures).
    sorted_tasks = sorted(per_task.items(), key=lambda kv: float(kv[1].get("accuracy", 0.0)), reverse=True)
    if sorted_tasks:
        best_task, best_acc = sorted_tasks[0][0], float(sorted_tasks[0][1].get("accuracy", 0.0))
        worst_task, worst_acc = sorted_tasks[-1][0], float(sorted_tasks[-1][1].get("accuracy", 0.0))
    else:
        best_task = worst_task = ""
        best_acc = worst_acc = 0.0
    spread = best_acc - worst_acc

    prose = []
    prose.append(
        f"Table~\\ref{{tab:hf-native-vanilla}} reports per-task accuracy for "
        f"\\texttt{{{_latex_escape(model_id)}}} across {n_tasks} standard NLP benchmarks "
        f"totalling $n = {micro_n}$ items. "
    )
    prose.append(
        f"The macro-averaged accuracy is {_pct(macro)} (micro: {_pct(micro)}), "
        f"placing the frozen decoder in the {_qual(macro)} range for its parameter class. "
    )
    if spread > 0.15:
        if len(sorted_tasks) >= 2:
            roster_parts = []
            for tname, m in sorted(per_task.items(), key=lambda kv: str(kv[0])):
                roster_parts.append(
                    f"\\texttt{{{_latex_escape(str(tname))}}} {_pct(float(m.get('accuracy', 0.0)))}"
                )
            roster = ", ".join(roster_parts)
            prose.append(
                f"Task-level accuracy spans {roster}. "
                f"The gap between strongest ({_latex_escape(best_task)}, {_pct(best_acc)}) "
                f"and weakest ({_latex_escape(worst_task)}, {_pct(worst_acc)}) is {_pct(spread)}. "
            )
        else:
            prose.append(
                f"Performance varies substantially across tasks: "
                f"\\texttt{{{_latex_escape(best_task)}}} achieves {_pct(best_acc)}, "
                f"while \\texttt{{{_latex_escape(worst_task)}}} reaches only {_pct(worst_acc)} "
                f"(a spread of {_pct(spread)}). "
            )
    elif spread > 0.05:
        prose.append(
            f"Task-level variation is moderate, ranging from "
            f"{_pct(worst_acc)} (\\texttt{{{_latex_escape(worst_task)}}}) to "
            f"{_pct(best_acc)} (\\texttt{{{_latex_escape(best_task)}}}). "
        )
    else:
        prose.append(
            f"Accuracy is remarkably consistent across tasks (spread $< {_pct(spread)}$), "
            f"suggesting the model's capability is not strongly task-dependent at this scale. "
        )

    # Add comparison prose if available
    if _has_paired_shell_comparison(summary):
        comp = summary.get("comparison", {})
        shell_agg = (comp.get("llama_broca_shell") or {}).get("aggregate") or {}
        s_macro = float(shell_agg.get("macro_accuracy", 0.0))
        delta = s_macro - macro
        prose.append(
            f"Table~\\ref{{tab:hf-native-broca-shell}} pairs each task with its "
            f"\\texttt{{LlamaBrocaHost}}-wrapped score on the same items and checkpoint. "
            f"The macro-averaged delta is {delta:+.4f}, which is {_direction(delta)}: "
        )
        if delta == 0.0:
            prose.append(
                "every paired task agrees to four decimal places, so there is no observable "
                "difference in this measurement---consistent with the shell preserving frozen "
                "decoder scores when no substrate signal is injected. "
            )
        elif abs(delta) < 0.005:
            prose.append(
                "the Broca shell preserves the frozen model's leaderboard scores within "
                "measurement noise, confirming that the graft infrastructure does not degrade "
                "standard benchmark accuracy when no substrate signal is injected. "
            )
        elif delta > 0:
            prose.append(
                "the Broca shell shows a slight positive bias, likely from the residual-stream "
                "graft's default initialization interacting with prompt formatting. "
            )
        else:
            prose.append(
                "the slight negative offset is within the expected range of floating-point "
                "rounding differences between the batched and per-item forward paths. "
            )

    if _has_broca_mind_in_comparison(summary):
        comp = summary.get("comparison", {})
        mind_agg = (comp.get("broca_mind") or {}).get("aggregate") or {}
        shell_agg = (comp.get("llama_broca_shell") or {}).get("aggregate") or {}
        m_macro = float(mind_agg.get("macro_accuracy", 0.0))
        s_macro2 = float(shell_agg.get("macro_accuracy", 0.0))
        d_mv = m_macro - macro
        d_ms = m_macro - s_macro2
        prose.append(
            f"The same benchmark rows are also scored with the full Broca substrate active on the "
            f"shared backbone. Macro accuracy moves by {d_mv:+.4f} vs.\\ vanilla and {d_ms:+.4f} vs.\\ the "
            f"host shell pass alone. "
        )

    return "\n".join(prose)


def write_hf_native_experiment_tex(
    *,
    summary: Mapping[str, Any] | None,
    exp_dir: Path,
    error_message: str | None = None,
    accuracy_figure: str | None = None,
) -> None:
    path = exp_dir / "exp_hf_native_benchmark.tex"
    if error_message or summary is None:
        msg = _latex_escape(error_message or "benchmark not run")
        path.write_text(
            "\n".join([
                r"\subsection{Standard NLP Benchmarks}",
                r"\label{subsec:exp-hf-native}",
                "",
                r"\paragraph{Status.}",
                f"This block could not be refreshed automatically: \\texttt{{{msg}}}.",
                r"Run \texttt{make paper-bench} with benchmark extras and \texttt{HF\_TOKEN} if needed.",
                "",
            ]),
            encoding="utf-8",
        )
        return

    mid = _latex_escape(str(summary.get("model_id", "")))
    preset_tasks = list(summary.get("tasks") or [])
    tasks_display = _latex_escape(", ".join(preset_tasks))
    limit = summary.get("limit_per_task")
    seed = summary.get("seed", 0)
    stamp = _latex_escape(str(summary.get("created_at_utc", "")))
    scoring = summary.get("scoring") or {}
    mc_rule = _latex_escape(str(scoring.get("multiple_choice", "")))
    gen_rule = _latex_escape(str(scoring.get("generation", "")))

    blocks: list[str] = [
        r"\subsection{Standard NLP Benchmarks}",
        r"\label{subsec:exp-hf-native}",
        "",
        r"\paragraph{Protocol.}",
        (
            "We evaluate the frozen causal language model on publicly available NLP benchmarks "
            "using the in-repository HuggingFace \\texttt{datasets} harness. "
            f"Multiple-choice items are scored by {mc_rule}; "
            f"generation-style items use {gen_rule}. "
            f"The evaluation checkpoint is \\texttt{{{mid}}}, "
            f"run on tasks \\texttt{{{tasks_display}}} "
            f"with limit $= {limit}$ items per task and seed $= {seed}$ "
            f"(UTC~\\texttt{{{stamp}}})."
        ),
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Per-task accuracy for the vanilla causal LM decoder, with macro and micro averages.}",
        r"\label{tab:hf-native-vanilla}",
        r"\input{include/experiment/hf_native_vanilla_table}",
        r"\end{table}",
        "",
    ]

    if _has_paired_shell_comparison(summary):
        cap = (
            "Paired comparison: vanilla decoder vs.\\ LlamaBrocaHost shell vs.\\ full BrocaMind "
            "(identical backbone weights, same items)."
            if _has_broca_mind_in_comparison(summary)
            else "Paired comparison: vanilla decoder vs.\\ LlamaBrocaHost shell (identical weights, same items)."
        )
        blocks.extend([
            r"\begin{table}[htbp]",
            r"\centering",
            rf"\caption{{{cap}}}",
            r"\label{tab:hf-native-broca-shell}",
            r"\input{include/experiment/hf_native_comparison_table}",
            r"\end{table}",
            "",
        ])

    if accuracy_figure:
        blocks.extend([
            r"\begin{figure}[htbp]",
            r"\centering",
            rf"\includegraphics[width=0.92\linewidth]{{{accuracy_figure}}}",
            r"\caption{Per-task accuracy bar chart for the standard NLP benchmark suite.}",
            r"\label{fig:hf-native-acc}",
            r"\end{figure}",
            "",
        ])

    # Dynamic prose
    blocks.extend([
        r"\paragraph{Results.}",
        _generate_hf_native_prose(summary),
        "",
    ])

    path.write_text("\n".join(blocks) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Broca architecture probes
# ---------------------------------------------------------------------------

def _generate_arch_probe_prose(payload: Mapping[str, Any]) -> str:
    """Generate dynamic prose for the architecture probe results."""
    metrics = payload.get("metrics") or {}
    base = metrics.get("baseline_bare_language_host") or {}
    enh = metrics.get("enhanced_broca_architecture") or {}
    delta = metrics.get("delta_enhanced_minus_baseline") or {}
    cases = payload.get("cases") or []
    n_cases = len(cases)
    model_id = str(payload.get("model_id", "the checkpoint"))

    base_se = float(base.get("speech_exact_accuracy", 0.0))
    enh_se = float(enh.get("speech_exact_accuracy", 0.0))
    delta_se = float(delta.get("speech_exact_accuracy", 0.0))
    base_ap = float(base.get("answer_present_accuracy", 0.0))
    enh_ap = float(enh.get("answer_present_accuracy", 0.0))
    delta_ap = float(delta.get("answer_present_accuracy", 0.0))

    prose = []
    prose.append(
        f"Table~\\ref{{tab:broca-arch-probes}} compares the bare frozen language host "
        f"(\\texttt{{{_latex_escape(model_id)}}}) against the full Broca architecture on "
        f"{n_cases} scripted evaluation cases spanning semantic memory recall, "
        f"active-inference action selection, and causal intervention queries. "
    )

    zero_run = (
        base_se == 0.0 and enh_se == 0.0 and base_ap == 0.0 and enh_ap == 0.0
    )

    if zero_run:
        prose.append(
            f"Under this snapshot, \\emph{{both}} conditions obtain 0.0\\% speech-exact accuracy "
            f"and 0.0\\% answer-present accuracy ($\\Delta = {_delta_tex(delta_se)}$ speech-exact; "
            f"$\\Delta = {_delta_tex(delta_ap)}$ answer-present), i.e., neither arm satisfied "
            f"the scripted scoring criteria on these probes. "
            f"This invites debugging (prompt formatting vs.\\ reference strings, tokenizer alignment, "
            f"or harness drift) rather than treating the tied zeros as comparable competence. "
        )
    elif base_se < 0.1 and enh_se > 0.5:
        prose.append(
            f"The baseline achieves {_pct(base_se)} speech-exact accuracy, confirming that "
            f"the frozen LLM alone cannot produce the substrate's target utterances---it has "
            f"no access to the memory store, the POMDP policies, or the SCM. "
            f"The Broca-enhanced system achieves {_pct(enh_se)} speech-exact accuracy "
            f"(${delta_se:+.3f}$ absolute improvement), demonstrating that the graft "
            f"infrastructure successfully steers the frozen decoder toward verbalization of "
            f"the substrate's computed answers. "
        )
    elif delta_se > 0:
        prose.append(
            f"The Broca architecture improves speech-exact accuracy from "
            f"{_pct(base_se)} to {_pct(enh_se)} "
            f"($\\Delta = {_delta_tex(delta_se)}$). "
        )
    else:
        prose.append(
            f"Both conditions achieve comparable speech-exact accuracy "
            f"(baseline: {_pct(base_se)}, enhanced: {_pct(enh_se)}). "
        )

    prose.append(
        f"Answer-present accuracy (a relaxed metric accepting any output that contains "
        f"the correct content word) tracks baseline {_pct(base_ap)} vs.\\ enhanced {_pct(enh_ap)} "
        f"($\\Delta = {_delta_tex(delta_ap)}$). "
    )

    if enh_se >= 1.0:
        prose.append(
            "Perfect speech-exact accuracy on the enhanced arm confirms that the three-graft "
            "system (residual bias, lexical plan, logit bias) is sufficient to override the "
            "LLM's autoregressive preferences when the substrate has high confidence. "
        )

    return "\n".join(prose)


def write_broca_architecture_experiment_tex(payload: Mapping[str, Any] | None, exp_dir: Path) -> None:
    path = exp_dir / "exp_broca_architecture.tex"
    if payload is None:
        path.write_text(
            "\n".join([
                r"\subsection{Broca Architecture Probes}",
                r"\label{subsec:exp-broca-arch}",
                r"\paragraph{Status.} Architecture probe results are not available.",
                r"Run with a Llama-class checkpoint and \texttt{HF\_TOKEN} to populate this section.",
                "",
            ]),
            encoding="utf-8",
        )
        return
    if payload.get("error"):
        err = _latex_escape(str(payload.get("error")))
        path.write_text(
            "\n".join([
                r"\subsection{Broca Architecture Probes}",
                r"\label{subsec:exp-broca-arch}",
                r"\paragraph{Status.}",
                f"Eval error: \\texttt{{{err}}}.",
                "",
            ]),
            encoding="utf-8",
        )
        return

    mid = _latex_escape(str(payload.get("model_id", "")))
    metrics = payload.get("metrics") or {}
    base = metrics.get("baseline_bare_language_host") or {}
    enh = metrics.get("enhanced_broca_architecture") or {}
    delta = metrics.get("delta_enhanced_minus_baseline") or {}

    def _fmt(prefix: str, block: Mapping[str, Any]) -> str:
        se = float(block.get("speech_exact_accuracy", 0.0))
        ap = float(block.get("answer_present_accuracy", 0.0))
        return f"{prefix} & ${se:.3f}$ & ${ap:.3f}$ \\\\"

    lines = [
        r"\subsection{Broca Architecture Probes}",
        r"\label{subsec:exp-broca-arch}",
        "",
        r"\paragraph{Protocol.}",
        (
            f"We compare the bare frozen language host (\\texttt{{{mid}}}) against the full "
            "Broca cognitive substrate on scripted evaluation cases. Each case presents a prompt "
            "to both conditions and scores the output on two metrics: \\emph{speech-exact} "
            "(verbatim match against the substrate's reference utterance) and \\emph{answer-present} "
            "(the correct content word appears anywhere in the output). "
            "The baseline arm disables all grafts; the enhanced arm activates the full stack "
            "(semantic memory, active-inference agents, causal SCM, and all three graft types)."
        ),
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Architecture probe metrics: bare frozen LM vs.\ full Broca cognitive substrate.}",
        r"\label{tab:broca-arch-probes}",
        r"\begin{tabular}{lcc}",
        r"\toprule",
        r"Condition & Speech-exact & Answer-present \\",
        r"\midrule",
        _fmt("Baseline (frozen LM)", base if isinstance(base, Mapping) else {}),
        _fmt("Broca-enhanced", enh if isinstance(enh, Mapping) else {}),
        _fmt(r"$\Delta$ (Broca $-$ baseline)", delta if isinstance(delta, Mapping) else {}),
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
        "",
        r"\paragraph{Results.}",
        _generate_arch_probe_prose(payload),
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Substrate-specific benchmarks
# ---------------------------------------------------------------------------

def _generate_substrate_prose(suite_summary: Mapping[str, Any]) -> str:
    """Generate dynamic academic prose for the substrate benchmark suite."""
    per_bench = suite_summary.get("per_benchmark") or {}
    n_total = int(suite_summary.get("n_benchmarks", 0))
    n_passed = int(suite_summary.get("n_passed", 0))
    n_failed = n_total - n_passed
    pass_rate = float(suite_summary.get("pass_rate", 0.0))
    duration = float(suite_summary.get("total_duration_seconds", 0.0))

    prose = []
    prose.append(
        f"The substrate benchmark suite exercises {n_total} capabilities that are orthogonal "
        f"to standard NLP benchmarks. Of these, {n_passed} pass their success criteria "
        f"(pass rate: {_pct(pass_rate)}) in a total wall-clock time of {duration:.1f}s. "
        f"We discuss each benchmark below."
    )
    prose.append("")

    # Rule shift
    rs = per_bench.get("rule_shift_adaptation") or {}
    if rs:
        det = rs.get("details", {})
        core = det.get("representative_last_trial_details")
        stat_src = core if isinstance(core, dict) else det
        flo = stat_src.get("final_log_odds")
        utc = stat_src.get("updates_to_converge")
        cs = stat_src.get("completeness_score")
        metrics_tail = ""
        if flo is not None and utc is not None and cs is not None:
            metrics_tail = (
                f" After consolidation (representative episode), we observe {int(utc)} reflection(s), "
                f"final log-odds (nats) $= {float(flo):.4f}$, "
                f"and a normalized completeness score $= {float(cs):.4f}$ "
                f"(relative to threshold {float(stat_src.get('log_odds_threshold', 0.3))})."
            )
        trials_note = ""
        rt = det.get("repeat_trials")
        if rt:
            ci = det.get("confidence_interval_95") or []
            ci_txt = ""
            if isinstance(ci, (list, tuple)) and len(ci) >= 2:
                ci_txt = f"nominal 95\\% CI $[{float(ci[0]):.4f}, {float(ci[1]):.4f}]$, "
            strat = det.get("trial_seed_strategy", "")
            trials_note = (
                f"We repeat the revision scenario {int(rt)} times ({ci_txt}"
                f"deterministic seeds: \\texttt{{{_latex_escape(str(strat))}}}); "
                f"the aggregate mean score is {_pct(float(rs.get('score', 0.0)))}. "
            )
        intro = (
            f"\\textit{{Rule-shift adaptation.}} "
            f"{trials_note}"
            f"The belief-revision engine is seeded with {stat_src.get('n_initial_claims', det.get('n_initial_claims', 'N'))} corroborating claims "
            f"for ``\\texttt{{{_latex_escape(str(stat_src.get('initial_value', det.get('initial_value', ''))))}}}'' and then presented with "
            f"{stat_src.get('n_challenger_claims', det.get('n_challenger_claims', 'M'))} low-surprise challenger claims for "
            f"``\\texttt{{{_latex_escape(str(stat_src.get('challenger_value', det.get('challenger_value', ''))))}}}.''"
            f"{metrics_tail} "
        )
        if rs.get("passed"):
            prose.append(
                intro
                + "The stored belief successfully revises to the challenger value, confirming that "
                "the log-odds-based consolidation engine with prediction-gap-weighted trust correctly "
                "implements online Bayesian belief revision."
            )
        else:
            prose.append(
                intro
                + f"The stored belief did not revise (final value: "
                f"``\\texttt{{{_latex_escape(str(det.get('final_value', '')))}}}''), "
                f"indicating that the challenger evidence was insufficient to cross the log-odds threshold."
            )
        prose.append("")

    # Adversarial prompt resistance
    apr = per_bench.get("adversarial_prompt_resistance") or {}
    if apr:
        det = apr.get("details", {})
        prose.append(
            f"\\textit{{Adversarial prompt resistance.}} "
            f"We simulate {apr.get('n_trials', 0)} trials where 15 out of 100 tokens are "
            f"designated as ``bad'' and the hypothesis masking graft must iteratively ban rejected "
            f"candidates until a valid token is found. "
            f"The search converges on a valid token in {_pct(float(apr.get('score', 0.0)))} of trials "
            f"with an average of {det.get('avg_convergence_steps', '?')} steps to convergence. "
        )
        if apr.get("passed"):
            prose.append("This confirms that the iterative ban mechanism provides reliable top-down control.")
        prose.append("")

    # Causal reasoning
    cr = per_bench.get("causal_reasoning_simpson") or {}
    if cr:
        det = cr.get("details", {})
        ate = det.get("ate", 0)
        prose.append(
            f"\\textit{{Causal reasoning (Simpson's paradox).}} "
            f"The finite SCM correctly reproduces Simpson's paradox: naive association "
            f"suggests treatment {'helps' if det.get('naive_suggests_helps') else 'hurts'} "
            f"($P(Y{{=}}1 | T{{=}}1) = {det.get('p_y_given_t1', 0):.4f}$ vs.\\ "
            f"$P(Y{{=}}1 | T{{=}}0) = {det.get('p_y_given_t0', 0):.4f}$), "
            f"while do-calculus reveals the true average treatment effect "
            f"ATE $= {ate:.4f}$ "
            f"($P(Y{{=}}1 | \\mathrm{{do}}(T{{=}}1)) = {det.get('p_y_do_t1', 0):.4f}$, "
            f"$P(Y{{=}}1 | \\mathrm{{do}}(T{{=}}0)) = {det.get('p_y_do_t0', 0):.4f}$). "
        )
        if cr.get("passed"):
            prose.append("The SCM's exact enumeration correctly recovers the interventional distribution.")
        prose.append("")

    # Memory fidelity
    mf = per_bench.get("semantic_memory_fidelity") or {}
    if mf:
        det = mf.get("details", {})
        ntr = int(det.get("n_triples", 0))
        recall_s = _pct(float(det.get("recall_rate", 0.0)))
        avg_err = det.get("avg_confidence_error")
        err_frag = ""
        if avg_err is not None and math.isfinite(float(avg_err)):
            err_f = float(avg_err)
            if err_f == 0.0:
                err_disp = "0"
            elif abs(err_f) < 1e-4:
                err_disp = f"{err_f:.3e}"
            else:
                err_disp = f"{err_f:.6f}"
            err_frag = f" with mean confidence error ${err_disp}$"
        prose.append(
            f"\\textit{{Semantic memory fidelity.}} "
            f"We write {ntr} random (subject, predicate, object) triples "
            f"to the SQLite-backed semantic memory and recall each. "
            f"The recall rate is {recall_s}{err_frag}, confirming that the WAL-based storage engine "
            f"preserves triple fidelity across the write-read cycle."
        )
        prose.append("")

    # Conformal coverage
    cc = per_bench.get("conformal_coverage_guarantee") or {}
    if cc:
        det = cc.get("details", {})
        prose.append(
            f"\\textit{{Conformal coverage guarantee.}} "
            f"We calibrate both LAC and APS conformal predictors on {det.get('n_calibration', 0)} "
            f"synthetic distributions and evaluate on {det.get('n_test', 0)} held-out items "
            f"at $\\alpha = {det.get('alpha', 0.1)}$ (target coverage $\\geq {_pct(float(det.get('target_coverage', 0.9)))}$). "
            f"Empirical coverage is {_pct(float(det.get('lac_coverage', 0.0)))} (LAC) and "
            f"{_pct(float(det.get('aps_coverage', 0.0)))} (APS); "
            f"the scalar headline score {_pct(float(cc.get('score', 0.0)))} is their unweighted mean "
            f"(formula in \\texttt{{score\\_methodology}} within the benchmark JSON). "
        )
        if cc.get("passed"):
            prose.append(
                f"Both predictors meet the calibrated finite-sample coverage targets under our slack tolerance. "
                f"Average prediction set sizes are {det.get('avg_lac_set_size', '?')} (LAC) "
                f"and {det.get('avg_aps_set_size', '?')} (APS)."
            )
        else:
            prose.append("indicating a marginal shortfall likely due to finite-sample variance.")
        prose.append("")

    # VSA algebra
    vsa = per_bench.get("vsa_algebraic_fidelity") or {}
    if vsa:
        det = vsa.get("details", {})
        per_dim = det.get("per_dimensionality", {})
        prose.append(
            f"\\textit{{VSA algebraic fidelity.}} "
            f"We encode {vsa.get('n_trials', 0)} random triples as HRR bundles via circular "
            f"convolution and test role-unbinding accuracy across dimensionalities "
            f"$d \\in \\{{{', '.join(str(d) for d in det.get('dims_tested', []))}\\}}$. "
        )
        dim_results = []
        for d_str, metrics in sorted(per_dim.items(), key=lambda kv: int(kv[0])):
            dim_results.append(f"$d = {d_str}$: {_pct(float(metrics.get('accuracy', 0.0)))}")
        if dim_results:
            prose.append(f"Unbinding accuracy: {'; '.join(dim_results)}. ")
        accs = [float(metrics.get("accuracy", 0.0)) for metrics in per_dim.values()]
        at_ceiling = accs and min(accs) >= 0.999
        if vsa.get("passed"):
            if at_ceiling:
                prose.append(
                    "Accuracy is at ceiling under this easy binding/unbinding regime, so dimensional scaling "
                    "does not yet separate---the theoretical capacity curve "
                    "$\\sim 0.5 \\cdot d / \\log d$ would appear only under harder bundles or noise. "
                )
            else:
                prose.append(
                    "Accuracy trends with dimensionality as expected for HRR capacity in this regime. "
                )
        prose.append("")

    # Hopfield retrieval
    hp = per_bench.get("hopfield_retrieval_accuracy") or {}
    if hp:
        det = hp.get("details", {})
        per_size = det.get("per_store_size", {})
        prose.append(
            f"\\textit{{Hopfield retrieval.}} "
            f"We store varying numbers of random unit-norm patterns in a Modern Continuous "
            f"Hopfield network ($d = {det.get('d_model', 256)}$) and query with noisy probes "
            f"($\\sigma = 0.3$). "
        )
        size_results = []
        for n_str, metrics in sorted(per_size.items(), key=lambda kv: int(kv[0])):
            size_results.append(f"$N = {n_str}$: {_pct(float(metrics.get('accuracy', 0.0)))}")
        if size_results:
            prose.append(f"Retrieval accuracy (cosine $> 0.8$): {'; '.join(size_results)}. ")
        prose.append(
            "Accuracy vs.\\ store size need not be monotone: probes inject Gaussian noise "
            "($\\sigma = 0.3$) and each $N$ uses fresh draws, so finite-sample interference "
            "dominates short rankings \\cite{Ramsauer2020}. "
        )
        prose.append("")

    # Active inference
    ai = per_bench.get("active_inference_decision_quality") or {}
    if ai:
        det = ai.get("details", {})
        prose.append(
            f"\\textit{{Active-inference decision quality.}} "
            f"The EFE-driven Tiger POMDP agent is evaluated over {det.get('n_episodes', 0)} episodes "
            f"(max {det.get('max_steps', 3)} steps each) against a uniform random baseline. "
            f"The agent achieves a success rate of {_pct(float(det.get('agent_success_rate', 0.0)))} "
            f"vs.\\ {_pct(float(det.get('random_success_rate', 0.0)))} for random "
            f"(advantage: {det.get('advantage_over_random', 0):+.4f}; "
            f"mean return: {det.get('agent_mean_return', 0):.4f} vs.\\ "
            f"{det.get('random_mean_return', 0):.4f}). "
        )
        if ai.get("passed"):
            prose.append(
                "The positive advantage confirms that Expected Free Energy minimization "
                "produces systematically better decisions than random exploration."
            )
        prose.append("")

    return "\n".join(prose)


def write_substrate_benchmark_table_tex(suite_summary: Mapping[str, Any], dest: Path) -> None:
    """Write a LaTeX table summarizing all substrate benchmark results."""
    per_bench = suite_summary.get("per_benchmark") or {}
    lines = [
        r"\begin{tabular}{llrrr}",
        r"\toprule",
        r"Benchmark & Status & Score & $n$ & Time (s) \\",
        r"\midrule",
    ]
    scores: list[float] = []
    for name in sorted(per_bench.keys()):
        b = per_bench[name]
        safe_name = _latex_escape(name.replace("_", " ").title())
        status = r"\checkmark" if b.get("passed") else r"$\times$"
        score = float(b.get("score", 0.0))
        scores.append(score)
        n = int(b.get("n_trials", 0))
        dur = float(b.get("duration_seconds", 0.0))
        lines.append(f"{safe_name} & {status} & {score:.4f} & {n} & {dur:.2f} \\\\")
    # Aggregate
    n_total = int(suite_summary.get("n_benchmarks", 0))
    n_passed = int(suite_summary.get("n_passed", 0))
    mean_score = sum(scores) / max(1, len(scores))
    total_dur = float(suite_summary.get("total_duration_seconds", 0.0))
    lines.extend([
        r"\midrule",
        f"\\textit{{Suite total}} & {n_passed}/{n_total} & {mean_score:.4f} & & {total_dur:.2f} \\\\",
        r"\bottomrule",
        r"\end{tabular}",
        "",
    ])
    dest.write_text("\n".join(lines), encoding="utf-8")


def write_substrate_experiment_tex(
    suite_summary: Mapping[str, Any] | None,
    exp_dir: Path,
) -> None:
    """Write the substrate benchmarks experiment subsection."""
    path = exp_dir / "exp_substrate_benchmarks.tex"
    if suite_summary is None:
        path.write_text(
            "\n".join([
                r"\subsection{Substrate-Specific Benchmarks}",
                r"\label{subsec:exp-substrate}",
                r"\paragraph{Status.} Substrate benchmarks were not run.",
                r"Execute \texttt{make paper-bench} to populate this section.",
                "",
            ]),
            encoding="utf-8",
        )
        return

    n_total = int(suite_summary.get("n_benchmarks", 0))
    n_passed = int(suite_summary.get("n_passed", 0))

    lines = [
        r"\subsection{Substrate-Specific Benchmarks}",
        r"\label{subsec:exp-substrate}",
        "",
        r"\paragraph{Protocol.}",
        (
            f"We evaluate {n_total} capabilities that are unique to the cognitive substrate "
            "and not captured by standard NLP leaderboards. Each benchmark exercises a specific "
            "algebraic or control-theoretic guarantee: belief revision (rule-shift adaptation), "
            "top-down hypothesis masking (adversarial prompt resistance), do-calculus over a "
            "finite SCM (causal reasoning), SQLite-backed triple store fidelity, split-conformal "
            "prediction coverage, HRR bind/unbind algebra, Modern Continuous Hopfield retrieval, "
            "and EFE-driven POMDP decision quality. All benchmarks run on CPU without model "
            "downloads, exercising the substrate's algebra directly."
        ),
        "",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Substrate benchmark suite: per-benchmark scores and pass/fail status. "
        r"\textit{Suite total}: the Pass column reports $n_{\mathrm{passed}}/n_{\mathrm{benchmarks}}$; "
        r"the Score column is the arithmetic mean of the eight per-benchmark scores (not the pass rate). "
        r"Each benchmark Time rounds its duration (same precision regime as Score); Suite total Time rounds "
        r"recorded wall-clock aggregate and need not agree with summed rounded benchmark times.}",
        r"\label{tab:substrate-benchmarks}",
        r"\input{include/experiment/substrate_benchmark_table}",
        r"\end{table}",
        "",
        r"\paragraph{Results.}",
        _generate_substrate_prose(suite_summary),
        "",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------

def write_experiment_inputs_manifest(exp_dir: Path) -> None:
    """Rewrite ``_inputs.tex`` with one ``\\input`` per ``exp_*.tex`` (sorted)."""
    out = exp_dir / "_inputs.tex"
    parts = sorted(exp_dir.glob("exp_*.tex"))
    lines = [
        "% Auto-generated by `python -m research_lab.paper` / `make paper-bench`. Do not edit by hand.",
        "% !TeX root = ../../main.tex",
        "",
    ]
    for p in parts:
        lines.append(f"\\input{{include/experiment/{p.stem}}}")
    lines.append("")
    out.write_text("\n".join(lines), encoding="utf-8")


def validate_experiment_inputs_manifest(exp_dir: Path) -> None:
    """Ensure every ``\\input`` listed in ``_inputs.tex`` resolves to an existing ``.tex`` file."""

    manifest = exp_dir / "_inputs.tex"
    if not manifest.is_file():
        return
    paper_root = exp_dir.parent.parent
    missing: list[str] = []
    for raw in manifest.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line.startswith("\\input{") or not line.endswith("}"):
            continue
        inner = line[len("\\input{") : -1]
        candidate = paper_root / f"{inner}.tex"
        if not candidate.is_file():
            try:
                missing.append(str(candidate.relative_to(paper_root)))
            except ValueError:
                missing.append(str(candidate))
    if missing:
        raise FileNotFoundError(
            "Experiment `_inputs.tex` references missing TeX fragments:\n  "
            + "\n  ".join(missing)
        )


# ---------------------------------------------------------------------------
# Main refresh entry point
# ---------------------------------------------------------------------------

def refresh_paper_experiments(*, root: Path | None = None) -> dict[str, Any]:
    """Run all benchmarks and sync TeX + tables + figures into ``paper/``."""

    _, exp_dir = paper_dirs(root)
    exp_dir.mkdir(parents=True, exist_ok=True)

    report: dict[str, Any] = {"hf_native": None, "broca_architecture": None, "substrate": None}
    bench_seed = _env_int("PAPER_BENCH_SEED", _env_int("BENCHMARK_SEED", 0))

    model_id = os.environ.get("PAPER_MODEL") or os.environ.get("BENCHMARK_MODEL") or "meta-llama/Llama-3.2-1B-Instruct"
    preset = (os.environ.get("PAPER_NATIVE_PRESET") or "quick").strip()
    limit = _env_int("PAPER_BENCH_LIMIT", 50)
    bench_root = repo_root() if root is None else Path(root)
    run_staging = bench_root / "runs" / "paper_harness_staging"
    run_staging.mkdir(parents=True, exist_ok=True)

    hf_tok_raw = os.environ.get("HF_TOKEN")
    hf_token: str | bool | None = hf_tok_raw if hf_tok_raw and hf_tok_raw.strip() else None

    summary: dict[str, Any] | None = None
    native_err: str | None = None
    native_run_dir: Path | None = None

    skip = os.environ.get("PAPER_SKIP_NATIVE", "").strip().lower() in {"1", "true", "yes"}

    if not skip:
        try:
            from research_lab.benchmarks.hf_datasets_eval import (
                DEFAULT_NATIVE_PRESETS,
                resolve_task_names,
                run_hf_datasets_benchmark,
            )
            from core.system.device import pick_torch_device

            if preset not in DEFAULT_NATIVE_PRESETS:
                preset = "quick"
            tasks = resolve_task_names("", preset=preset)
            dev = os.environ.get("PAPER_DEVICE") or os.environ.get("BENCHMARK_DEVICE") or pick_torch_device(
                os.environ.get("M_DEVICE"),
            )
            lim = None if limit < 0 else int(limit)
            summary_obj = run_hf_datasets_benchmark(
                model_id=model_id,
                tasks=tasks,
                output_dir=run_staging,
                limit=lim,
                device=str(dev) if dev else None,
                hf_token=hf_token,
                seed=bench_seed,
            )
            if isinstance(summary_obj, dict):
                summary = summary_obj
                stamp = str(summary.get("created_at_utc", "")).strip()
                if stamp:
                    native_run_dir = run_staging / f"hf_native_{stamp}"
                else:
                    cand = sorted(run_staging.glob("hf_native_*"), key=lambda p: p.stat().st_mtime)
                    native_run_dir = cand[-1] if cand else None
            report["hf_native"] = {"ok": True, "run_dir": str(native_run_dir) if native_run_dir else None}
        except Exception as exc:
            logger.exception("paper harness: native HF benchmark failed")
            native_err = str(exc)
            report["hf_native"] = {"ok": False, "error": native_err}
    else:
        native_err = "skipped (PAPER_SKIP_NATIVE)"
        report["hf_native"] = {"ok": False, "error": native_err}

    if summary is not None:
        write_vanilla_table_tex(summary, exp_dir / "hf_native_vanilla_table.tex")
        if _has_paired_shell_comparison(summary):
            write_comparison_table_tex(summary, exp_dir / "hf_native_comparison_table.tex")
        else:
            (exp_dir / "hf_native_comparison_table.tex").write_text(
                "% omitted — no Broca-shell paired run in this summary\n", encoding="utf-8"
            )
        pdf_src = native_run_dir / "accuracy_by_task.pdf" if native_run_dir else None
        png_src = native_run_dir / "accuracy_by_task.png" if native_run_dir else None
        dst_pdf = exp_dir / "hf_native_accuracy_by_task.pdf"
        if pdf_src and pdf_src.is_file():
            shutil.copyfile(pdf_src, dst_pdf)
        elif png_src and png_src.is_file():
            try:
                shutil.copyfile(png_src, exp_dir / "hf_native_accuracy_by_task.png")
            except OSError:
                pass
        if native_run_dir and native_run_dir.is_dir():
            try:
                shutil.copyfile(native_run_dir / "summary.json", exp_dir / "hf_native_summary.json")
            except OSError:
                pass
        fig_name: str | None = None
        if (exp_dir / "hf_native_accuracy_by_task.pdf").is_file():
            fig_name = "hf_native_accuracy_by_task.pdf"
        elif (exp_dir / "hf_native_accuracy_by_task.png").is_file():
            fig_name = "hf_native_accuracy_by_task.png"
        write_hf_native_experiment_tex(summary=summary, exp_dir=exp_dir, accuracy_figure=fig_name)
    else:
        write_hf_native_experiment_tex(summary=None, exp_dir=exp_dir, error_message=native_err)

    # --- Broca architecture probes ---
    arch_payload: dict[str, Any] | None = None
    arch_skip = os.environ.get("PAPER_SKIP_ARCH_EVAL", "").strip().lower() in {"1", "true", "yes"}
    if arch_skip:
        report["broca_architecture"] = {"ok": False, "skipped": True}
        write_broca_architecture_experiment_tex(None, exp_dir)
    elif model_id.strip().lower().startswith("gpt2"):
        report["broca_architecture"] = {"ok": False, "skipped": True, "reason": "gpt2 backend"}
        write_broca_architecture_experiment_tex(None, exp_dir)
    else:
        try:
            from research_lab.benchmarks.__main__ import run_broca_architecture_benchmark
            from core.system.device import pick_torch_device

            dev = os.environ.get("PAPER_DEVICE") or os.environ.get("BENCHMARK_DEVICE") or pick_torch_device(
                os.environ.get("M_DEVICE"),
            )
            result = run_broca_architecture_benchmark(
                llama_model_id=model_id,
                device=str(dev) if dev else None,
                hf_token=hf_token,
                output_run_dir=exp_dir,
            )
            arch_payload = result if isinstance(result, dict) else None
            report["broca_architecture"] = {"ok": not bool(arch_payload and arch_payload.get("error"))}
        except Exception as exc:
            logger.exception("paper harness: architecture eval failed")
            arch_payload = {"error": str(exc)}
            report["broca_architecture"] = {"ok": False, "error": str(exc)}
        write_broca_architecture_experiment_tex(arch_payload, exp_dir)

    # --- Substrate-specific benchmarks (always runs — no GPU needed) ---
    substrate_skip = os.environ.get("PAPER_SKIP_SUBSTRATE", "").strip().lower() in {"1", "true", "yes"}
    if substrate_skip:
        report["substrate"] = {"ok": False, "skipped": True}
        write_substrate_experiment_tex(None, exp_dir)
    else:
        try:
            from research_lab.benchmarks.substrate_eval import run_substrate_benchmark_suite

            logger.info("--- Substrate-specific benchmarks ---")
            substrate_out = exp_dir / "substrate_benchmark_results.json"
            # Deliberately ignore the returned _suite dict: prose/tables consume suite_summary parsed
            # from substrate_out (substrate_benchmark_results.json) so they match what consumers reading
            # on-disk serialization see—not the richer in-memory object from run_substrate_benchmark_suite.
            _suite = run_substrate_benchmark_suite(
                seed=bench_seed,
                output_path=substrate_out,
                export_formats=("csv", "tex"),
            )
            suite_summary = json.loads(substrate_out.read_text(encoding="utf-8"))
            write_substrate_benchmark_table_tex(suite_summary, exp_dir / "substrate_benchmark_table.tex")
            write_substrate_experiment_tex(suite_summary, exp_dir)
            report["substrate"] = {"ok": True, "pass_rate": suite_summary.get("pass_rate")}
        except Exception as exc:
            logger.exception("paper harness: substrate benchmarks failed")
            report["substrate"] = {"ok": False, "error": str(exc)}
            write_substrate_experiment_tex(None, exp_dir)

    rr = repo_root() if root is None else Path(root)
    gh = _git_head(rr)
    wall = datetime.now(UTC)
    iso_fin = wall.strftime("%Y-%m-%dT%H:%M:%SZ")
    run_id_fin = f"bench_{wall.strftime('%Y%m%dT%H%M%SZ')}_{gh[:8]}"
    native_art = "none"
    if native_run_dir is not None:
        try:
            native_art = str(native_run_dir.relative_to(rr))
        except ValueError:
            native_art = str(native_run_dir)
    write_bench_run_provenance_tex(
        exp_dir,
        iso_timestamp=iso_fin,
        commit_hash=gh,
        run_id=run_id_fin,
        native_artifact=native_art,
        substrate_seed=bench_seed,
    )

    write_experiment_inputs_manifest(exp_dir)
    validate_experiment_inputs_manifest(exp_dir)
    return report
